name = "prueba-tecnica-main"
main = "src/index.ts"
compatibility_date = "2026-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
# Valores públicos (si los hubiera) se ponen aquí.
# Las credenciales de base de datos y Cloudinary se subirán como SECRETOS.

[observability]
enabled = true
